nodeLinker: node-modules
yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "metro-config@*":
    dependencies:
      "metro-transform-worker": "*"
  "metro-transform-worker@*":
    dependencies:
      "metro-minify-uglify": "*"
  "react-native@*":
    dependencies:
      "yargs": "^15.3.1"
  "react-native-codegen@*":
    dependencies:
      "glob": "^7.1.1"
      "invariant": "^2.2.4"
