nodeLinker: node-modules
yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "metro-config@*":
    dependencies:
      "metro-transform-worker": "*"
  "metro-transform-worker@*":
    dependencies:
      "metro-minify-uglify": "*"